### ISSUE TITLE
Can I upload files with this wonderful library?

### ISSUE THREAD

**Issue by dewdad** [featurist/httpism#10]
If so, a code example would be greatly appreciated.

**Comment by refractalize** [comment]
hi @dewdad yes of course - do you mean posting raw files (binary) or as part of HTML forms?

The raw files one is fairly easy, just pass a stream as the second argument. See this commit in #11: https://github.com/featurist/httpism/blob/4cb95d2322d49091b6c694f0ff09cd40181ef597/readme.md#post-streams-and-files

**Comment by refractalize** [comment]
multipart (and docs) forms should be covered with with #12
