### ISSUE TITLE
How can I change options of an existing client?

### ISSUE THREAD

**Issue by leopku** [featurist/httpism#32]
```js
const client = httpism.client(baseURL, { headers: {...}});
client.post('/auth')
  .then(response => {
    ... // how to add authorized headers to the client?
  })
  ...

client.get(...) // something with credentials 
```

**Comment by refractalize** [comment]
hi @leopku you can create a new client there, setting headers as you have done on the first line. Alternatively, you can pass the credentials to `client.get(url, {headers})`.

But I think what you might be asking is, how can you modify the current client's options such that it's effectively logged in after your `/auth` call... you can do `client._options.headers = {authorization: ...}`. Then all subsequent calls will have the correct header.

You could also create some middleware that logged in on the first request with some credentials in the options, set the authorization header and then all subsequent calls would be authenticated already. One more option (!) is to use cookies to carry the authentication, you can create a new client that supports cookies with the `{cookies: true}` option - but this is quite different to using an `Authorization` header.

**Comment by leopku** [comment]
`client._options.headers = {authorization: ...}` is exactly what I need.
Thanks a lot.
